[package]
authors = ["Gabriel Luchtenberg <gabriel.luchtenber12@gmail.com>"]
edition = "2018"
name = "pipe-viewer"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
